<?
include('head/view/drawHead.php');
include('scripts/view/drawScripts.php');
include('widgets/view/drawWidgets.php');
include('forms/view/drawForms.php');
include('tariffs/view/DrawTariffsBlock.php');
include('tariffs/view/DrawTariffsTable.php');
include('preloader/view/drawPreloader.php');
include('navbar/view/drawNavBar.php');
include('navbar/view/drawTopLogo.php');
include('mainBlock/view/drawMainBlock.php');
include('mainBlock/view/drawHeroArea.php');
include('textBlock/view/drawTextBlock.php');
