<?
include('head/view/drawHead.php');
include('scripts/view/drawScripts.php');
include('widgets/view/drawWidgets.php');
include('loader/view/drawLoader.php');
include('navbar/view/drawNavBar.php');
include('mainBlock/view/drawMainBlock.php');
include('forms/view/drawForms.php');
include('textBlock/view/drawTextBlock.php');
include('aboutUs/view/drawAboutUsTop.php');
include('aboutUs/view/drawAboutUsBottom.php');
include('tariffs/view/DrawTariffsBlock.php');
include('tariffs/view/DrawTariffsTable.php');
include('carClasses/view/drawClasses.php');
