<?
include('text-for-deploy/htacces-text.php');
include('text-for-deploy/index-and-info-texts.php');
include('text-for-deploy/robot-texts.php');
include('text-for-deploy/sitemap.php');
include('utils/paths.php');
include('utils/deploy-functions.php');
include('utils/deploy-directions-and-transfers.php');
include('utils/deploy-sitemap.php');
include('utils/deploy-static-files.php');
include('utils/deploy-one-site.php');
